### ISSUE TITLE
AYUDA

### ISSUE THREAD

**Issue by AshiePleb** [eugeniodevv/Quesadilla#2]
[23:54:50 ERROR]: Encountered an unexpected exception
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3481) ~[?:?]
        at java.util.ArrayList.grow(ArrayList.java:237) ~[?:?]
        at java.util.ArrayList.grow(ArrayList.java:244) ~[?:?]
        at java.util.ArrayList.add(ArrayList.java:454) ~[?:?]
        at java.util.ArrayList.add(ArrayList.java:467) ~[?:?]
        at net.minecraft.server.v1_12_R1.DataWatcher.c(DataWatcher.java:215) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at net.minecraft.server.v1_12_R1.PacketPlayOutEntityMetadata.<init>(SourceFile:21) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:476) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at net.minecraft.server.v1_12_R1.PlayerList.postChunkLoadJoin(PlayerList.java:247) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at net.minecraft.server.v1_12_R1.PlayerList.lambda$null$0(PlayerList.java:199) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at net.minecraft.server.v1_12_R1.PlayerList$$Lambda$1087/0x000000080173caf0.run(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:146) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:434) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:163) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:981) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:775) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Quesadilla-"2f9e79d"]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by eugeniodevv** [comment]
spain please
